name: next_gen
description: NextGen App by Udyam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  google_sign_in: ^6.0.0
  intl: ">=0.18.1 <0.20.0"
  logger: ^2.0.2
  neopop: ^1.0.2
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
