name: next_gen
description: NextGen App by Udyam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.0
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  google_sign_in: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0
  intl: ">=0.18.1 <0.20.0"
  introduction_screen: ^3.1.0
  logger: ^2.0.2
  lottie: ^2.3.0
  neopop: ^1.0.2
  responsive_builder: ^0.7.0
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
