name: next_gen
description: NextGen App by Udyam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.0

  # Firebase Analytics commented out for now, will be implemented later
  # firebase_analytics: ^11.4.5
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  # No chart package dependency - using custom implementation
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_sign_in: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0
  intl: ">=0.18.1 <0.20.0"
  introduction_screen: ^3.1.0
  logger: ^1.3.0
  lottie: ^3.3.1
  neopop: ^1.0.2
  path_provider: ^2.1.1
  responsive_builder: ^0.7.0
  shimmer: ^3.0.0
  # Using cloud_firestore for search instead of Algolia due to dependency conflicts
  debounce_throttle: ^2.0.0

  cloud_firestore: any
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/animations/
