name: next_gen
description: NextGen App by Udyam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7 # For search module
  collection: ^1.18.0
  connectivity_plus: ^6.1.4
  debounce_throttle: ^2.0.0 # For search module

  # Firebase Analytics commented out for now, will be implemented later
  # firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  # No chart package dependency - using custom implementation
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.6.0
  get: ^4.6.5
  get_it: ^8.0.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.0.0
  heroicons: ^0.11.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ">=0.18.1 <0.20.0"
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.0
  logger: ^2.5.0
  lottie: ^3.3.1
  mime: ^1.0.4
  neopop: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  responsive_builder: ^0.7.0
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  timeago: ^3.7.1
  url_launcher: ^6.3.1
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  # Keep generate: true for now to support localization
  generate: true

  assets:
    - assets/images/
    - assets/animations/
