name: next_gen
description: NextGen App by Udyam
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc: ^9.0.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.6.5
  # Removed google_sign_in to avoid dependency conflicts
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  js: ^0.6.7
  intl: any
  logger: ^2.0.2+1
  neopop: ^1.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  fake_cloud_firestore: ^2.4.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
