// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqgFjXKoh67bjYcsAbdgdMpPF7QCYpNEE',
    appId: '1:91032840429:web:81ce18c1120eef75b884e4',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    authDomain: 'next-gen-udyam.firebaseapp.com',
    storageBucket: 'next-gen-udyam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqgFjXKoh67bjYcsAbdgdMpPF7QCYpNEE',
    appId: '1:91032840429:android:a63734335340c355b884e4',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlhFumhQ8ice4gh_utX2T5c5q1I-0ZZ4Q',
    appId: '1:91032840429:ios:3175a209c09c9edcb884e4',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.firebasestorage.app',
    iosClientId:
        '91032840429-mi0vep6nqklv7mgml89f38m50em03enp.apps.googleusercontent.com',
    iosBundleId: 'com.udyam.nextgen.next-gen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlhFumhQ8ice4gh_utX2T5c5q1I-0ZZ4Q',
    appId: '1:91032840429:macos:a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.firebasestorage.app',
    iosClientId:
        '91032840429-mi0vep6nqklv7mgml89f38m50em03enp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqgFjXKoh67bjYcsAbdgdMpPF7QCYpNEE',
    appId: '1:91032840429:windows:a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.firebasestorage.app',
  );
}
