// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for fuchsia platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMnLYQqLVLKGUqZZIbzZUTXMnTQUZXAE',
    appId: '1:91032840429:web:a9e9e9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    authDomain: 'next-gen-udyam.firebaseapp.com',
    storageBucket: 'next-gen-udyam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMnLYQqLVLKGUqZZIbzZUTXMnTQUZXAE',
    appId: '1:91032840429:android:a9e9e9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXMnLYQqLVLKGUqZZIbzZUTXMnTQUZXAE',
    appId: '1:91032840429:ios:a9e9e9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.appspot.com',
    iosClientId:
        '91032840429-a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9.apps.googleusercontent.com',
    iosBundleId: 'com.udyam.nextgen.nextGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXMnLYQqLVLKGUqZZIbzZUTXMnTQUZXAE',
    appId: '1:91032840429:macos:a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.appspot.com',
    iosClientId:
        '91032840429-a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9.apps.googleusercontent.com',
    iosBundleId: 'com.udyam.nextgen.nextGen.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMnLYQqLVLKGUqZZIbzZUTXMnTQUZXAE',
    appId: '1:91032840429:windows:a9e9e9f9f9f9f9f9f9f9f9f9f9f9f9f9',
    messagingSenderId: '91032840429',
    projectId: 'next-gen-udyam',
    storageBucket: 'next-gen-udyam.appspot.com',
  );
}
