name: Spell Check

# Workflow disabled as requested
on:
  workflow_dispatch:
    # This workflow will only run manually now

permissions:
  contents: write
  pull-requests: write

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: false # Disable caching for the action

      - name: Verify Flutter/Dart versions # Add this step
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7
        with:
          config: '.cspell.json'
          files: "{lib,test,docs}/**/*.{dart,md,yaml,json}"
          inline: warning
          incremental_files_only: false
          root: "."
